name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python build_readme.py
      - name: Commit and push if changed
        run: |
          git diff --quiet && exit 0
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add -A
          git commit -m "Update dynamic content"
          git push
